# Generated by Django 6.0.7 on 2026-07-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, verbose_name='Usuário')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('tipo_usuario', models.CharField(choices=[('ALUNO', 'Aluno'), ('PERSONAL', 'Personal Trainer'), ('ADMIN', 'Admin')], max_length=10, verbose_name='Perfil')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
    ]
