# Generated by Django 6.0.7 on 2026-08-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_aluno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
