# Generated by Django 6.0.7 on 2026-08-11 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_alter_aluno_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('grupo_muscular', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PlanoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('inicio', models.DateField()),
                ('final', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('F', 'Finalizado'), ('C', 'Cancelado')], default='A', max_length=1)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_treino', to='usuarios.aluno')),
            ],
            options={
                'verbose_name': 'Plano de Treino',
                'verbose_name_plural': 'Planos de treino',
                'ordering': ['inicio', 'aluno'],
            },
        ),
        migrations.CreateModel(
            name='SessaoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.IntegerField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('plano_treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='treinos.planotreino')),
            ],
            options={
                'verbose_name': 'Sessão de Treino',
                'verbose_name_plural': 'Sessões de treino',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='SessaoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=100)),
                ('repeticoes', models.IntegerField()),
                ('carga', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tempo_descanso', models.IntegerField(blank=True, null=True)),
                ('ordem', models.IntegerField(blank=True, null=True)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_aparece', to='treinos.exercicio')),
                ('sessao_treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios_da_sessao', to='treinos.sessaotreino')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
